---- MODULE sdw_policy ----

VARIABLE
    S_flying,
    S_pylon_inspection,
    S_manual_control_request,
    S_at_landing_position,
    S_mission_configuration,
    S_mission_started,
    S_being_blocked,
    S_being_blocked_notification,
    S_communication,
    S_communication_failure_notification,
    S_battery,
    S_low_battery_notification,
    S_critical_battery_notification,
    S_obstacle_detection,
    S_obstacle_detection_failure_notification,
    S_mission_abort_request

vars == <<S_flying, S_pylon_inspection, S_manual_control_request, S_at_landing_position, S_mission_configuration, S_mission_started, S_being_blocked, S_being_blocked_notification, S_communication, S_communication_failure_notification, S_battery, S_low_battery_notification, S_critical_battery_notification, S_obstacle_detection, S_obstacle_detection_failure_notification, S_mission_abort_request>>

Dom_S_flying == {"flying", "on_the_ground"}
Dom_S_pylon_inspection == {"complete", "not_complete"}
Dom_S_manual_control_request == {"on", "off"}
Dom_S_at_landing_position == {"yes", "no", "unknown"}
Dom_S_mission_configuration == {"configured", "not_configured"}
Dom_S_mission_started == {"yes", "no"}
Dom_S_being_blocked == {"yes", "no"}
Dom_S_being_blocked_notification == {"not_yet_notified", "notified"}
Dom_S_communication == {"stable", "degraded", "lost"}
Dom_S_communication_failure_notification == {"not_yet_notified", "notified"}
Dom_S_battery == {"ok", "low", "critical"}
Dom_S_low_battery_notification == {"not_yet_notified", "notified"}
Dom_S_critical_battery_notification == {"not_yet_notified", "notified"}
Dom_S_obstacle_detection == {"stable", "lost"}
Dom_S_obstacle_detection_failure_notification == {"not_yet_notified", "notified"}
Dom_S_mission_abort_request == {"yes", "no"}

TypeOK ==
    /\ S_flying \in Dom_S_flying
    /\ S_pylon_inspection \in Dom_S_pylon_inspection
    /\ S_manual_control_request \in Dom_S_manual_control_request
    /\ S_at_landing_position \in Dom_S_at_landing_position
    /\ S_mission_configuration \in Dom_S_mission_configuration
    /\ S_mission_started \in Dom_S_mission_started
    /\ S_being_blocked \in Dom_S_being_blocked
    /\ S_being_blocked_notification \in Dom_S_being_blocked_notification
    /\ S_communication \in Dom_S_communication
    /\ S_communication_failure_notification \in Dom_S_communication_failure_notification
    /\ S_battery \in Dom_S_battery
    /\ S_low_battery_notification \in Dom_S_low_battery_notification
    /\ S_critical_battery_notification \in Dom_S_critical_battery_notification
    /\ S_obstacle_detection \in Dom_S_obstacle_detection
    /\ S_obstacle_detection_failure_notification \in Dom_S_obstacle_detection_failure_notification
    /\ S_mission_abort_request \in Dom_S_mission_abort_request

NextTypeOK ==
    /\ S_flying' \in Dom_S_flying
    /\ S_pylon_inspection' \in Dom_S_pylon_inspection
    /\ S_manual_control_request' \in Dom_S_manual_control_request
    /\ S_at_landing_position' \in Dom_S_at_landing_position
    /\ S_mission_configuration' \in Dom_S_mission_configuration
    /\ S_mission_started' \in Dom_S_mission_started
    /\ S_being_blocked' \in Dom_S_being_blocked
    /\ S_being_blocked_notification' \in Dom_S_being_blocked_notification
    /\ S_communication' \in Dom_S_communication
    /\ S_communication_failure_notification' \in Dom_S_communication_failure_notification
    /\ S_battery' \in Dom_S_battery
    /\ S_low_battery_notification' \in Dom_S_low_battery_notification
    /\ S_critical_battery_notification' \in Dom_S_critical_battery_notification
    /\ S_obstacle_detection' \in Dom_S_obstacle_detection
    /\ S_obstacle_detection_failure_notification' \in Dom_S_obstacle_detection_failure_notification
    /\ S_mission_abort_request' \in Dom_S_mission_abort_request

take_off ==
        \/
            /\ S_flying = "on_the_ground"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "stable"
            /\ S_battery = "ok"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "on_the_ground"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "stable"
            /\ S_battery = "low"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "on_the_ground"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "degraded"
            /\ S_battery = "ok"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "on_the_ground"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "degraded"
            /\ S_battery = "low"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "on_the_ground"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "stable"
            /\ S_battery = "ok"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "on_the_ground"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "stable"
            /\ S_battery = "low"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "on_the_ground"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "degraded"
            /\ S_battery = "ok"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "on_the_ground"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "degraded"
            /\ S_battery = "low"
            /\ S_mission_abort_request = "no"
land ==
        \/
            /\ S_flying = "flying"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "lost"
        \/
            /\ S_flying = "flying"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_battery = "critical"
        \/
            /\ S_flying = "flying"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_mission_abort_request = "yes"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
go_to_landing_zone ==
        \/
            /\ S_flying = "flying"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "lost"
        \/
            /\ S_flying = "flying"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_battery = "critical"
        \/
            /\ S_flying = "flying"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_mission_abort_request = "yes"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
manual_control ==
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "stable"
            /\ S_battery = "ok"
            /\ S_obstacle_detection = "lost"
            /\ S_obstacle_detection_failure_notification = "not_yet_notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "stable"
            /\ S_battery = "low"
            /\ S_obstacle_detection = "lost"
            /\ S_obstacle_detection_failure_notification = "not_yet_notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "degraded"
            /\ S_battery = "ok"
            /\ S_obstacle_detection = "lost"
            /\ S_obstacle_detection_failure_notification = "not_yet_notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "degraded"
            /\ S_battery = "low"
            /\ S_obstacle_detection = "lost"
            /\ S_obstacle_detection_failure_notification = "not_yet_notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "yes"
            /\ S_being_blocked_notification = "not_yet_notified"
            /\ S_communication = "stable"
            /\ S_battery = "ok"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "yes"
            /\ S_being_blocked_notification = "not_yet_notified"
            /\ S_communication = "stable"
            /\ S_battery = "low"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "yes"
            /\ S_being_blocked_notification = "not_yet_notified"
            /\ S_communication = "degraded"
            /\ S_battery = "ok"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "yes"
            /\ S_being_blocked_notification = "not_yet_notified"
            /\ S_communication = "degraded"
            /\ S_battery = "low"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "degraded"
            /\ S_communication_failure_notification = "not_yet_notified"
            /\ S_battery = "ok"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "degraded"
            /\ S_communication_failure_notification = "not_yet_notified"
            /\ S_battery = "low"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "stable"
            /\ S_battery = "low"
            /\ S_low_battery_notification = "not_yet_notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "degraded"
            /\ S_battery = "low"
            /\ S_low_battery_notification = "not_yet_notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "stable"
            /\ S_battery = "ok"
            /\ S_obstacle_detection = "lost"
            /\ S_obstacle_detection_failure_notification = "not_yet_notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "stable"
            /\ S_battery = "low"
            /\ S_obstacle_detection = "lost"
            /\ S_obstacle_detection_failure_notification = "not_yet_notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "degraded"
            /\ S_battery = "ok"
            /\ S_obstacle_detection = "lost"
            /\ S_obstacle_detection_failure_notification = "not_yet_notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "degraded"
            /\ S_battery = "low"
            /\ S_obstacle_detection = "lost"
            /\ S_obstacle_detection_failure_notification = "not_yet_notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "stable"
            /\ S_battery = "ok"
            /\ S_obstacle_detection = "lost"
            /\ S_obstacle_detection_failure_notification = "not_yet_notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "stable"
            /\ S_battery = "low"
            /\ S_obstacle_detection = "lost"
            /\ S_obstacle_detection_failure_notification = "not_yet_notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "degraded"
            /\ S_battery = "ok"
            /\ S_obstacle_detection = "lost"
            /\ S_obstacle_detection_failure_notification = "not_yet_notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "degraded"
            /\ S_battery = "low"
            /\ S_obstacle_detection = "lost"
            /\ S_obstacle_detection_failure_notification = "not_yet_notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "yes"
            /\ S_being_blocked_notification = "not_yet_notified"
            /\ S_communication = "stable"
            /\ S_battery = "ok"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "yes"
            /\ S_being_blocked_notification = "not_yet_notified"
            /\ S_communication = "stable"
            /\ S_battery = "low"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "yes"
            /\ S_being_blocked_notification = "not_yet_notified"
            /\ S_communication = "degraded"
            /\ S_battery = "ok"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "yes"
            /\ S_being_blocked_notification = "not_yet_notified"
            /\ S_communication = "degraded"
            /\ S_battery = "low"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "yes"
            /\ S_being_blocked_notification = "not_yet_notified"
            /\ S_communication = "stable"
            /\ S_battery = "ok"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "yes"
            /\ S_being_blocked_notification = "not_yet_notified"
            /\ S_communication = "stable"
            /\ S_battery = "low"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "yes"
            /\ S_being_blocked_notification = "not_yet_notified"
            /\ S_communication = "degraded"
            /\ S_battery = "ok"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "yes"
            /\ S_being_blocked_notification = "not_yet_notified"
            /\ S_communication = "degraded"
            /\ S_battery = "low"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "degraded"
            /\ S_communication_failure_notification = "not_yet_notified"
            /\ S_battery = "ok"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "degraded"
            /\ S_communication_failure_notification = "not_yet_notified"
            /\ S_battery = "low"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "degraded"
            /\ S_communication_failure_notification = "not_yet_notified"
            /\ S_battery = "ok"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "degraded"
            /\ S_communication_failure_notification = "not_yet_notified"
            /\ S_battery = "low"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "stable"
            /\ S_battery = "low"
            /\ S_low_battery_notification = "not_yet_notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "degraded"
            /\ S_battery = "low"
            /\ S_low_battery_notification = "not_yet_notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "stable"
            /\ S_battery = "low"
            /\ S_low_battery_notification = "not_yet_notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "degraded"
            /\ S_battery = "low"
            /\ S_low_battery_notification = "not_yet_notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_manual_control_request = "on"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
        \/
            /\ S_flying = "flying"
            /\ S_manual_control_request = "on"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
        \/
            /\ S_flying = "flying"
            /\ S_manual_control_request = "on"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
execute_mission_task ==
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked_notification = "notified"
            /\ S_communication = "degraded"
            /\ S_communication_failure_notification = "notified"
            /\ S_battery = "low"
            /\ S_low_battery_notification = "notified"
            /\ S_obstacle_detection_failure_notification = "notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked_notification = "notified"
            /\ S_communication = "degraded"
            /\ S_communication_failure_notification = "notified"
            /\ S_battery = "low"
            /\ S_low_battery_notification = "notified"
            /\ S_obstacle_detection_failure_notification = "notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "no"
            /\ S_communication = "degraded"
            /\ S_communication_failure_notification = "notified"
            /\ S_battery = "low"
            /\ S_low_battery_notification = "notified"
            /\ S_obstacle_detection_failure_notification = "notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "no"
            /\ S_communication = "degraded"
            /\ S_communication_failure_notification = "notified"
            /\ S_battery = "low"
            /\ S_low_battery_notification = "notified"
            /\ S_obstacle_detection_failure_notification = "notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked_notification = "notified"
            /\ S_communication = "degraded"
            /\ S_communication_failure_notification = "notified"
            /\ S_battery = "low"
            /\ S_low_battery_notification = "notified"
            /\ S_obstacle_detection = "stable"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked_notification = "notified"
            /\ S_communication = "degraded"
            /\ S_communication_failure_notification = "notified"
            /\ S_battery = "low"
            /\ S_low_battery_notification = "notified"
            /\ S_obstacle_detection = "stable"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "no"
            /\ S_communication = "degraded"
            /\ S_communication_failure_notification = "notified"
            /\ S_battery = "low"
            /\ S_low_battery_notification = "notified"
            /\ S_obstacle_detection = "stable"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "no"
            /\ S_communication = "degraded"
            /\ S_communication_failure_notification = "notified"
            /\ S_battery = "low"
            /\ S_low_battery_notification = "notified"
            /\ S_obstacle_detection = "stable"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked_notification = "notified"
            /\ S_communication = "stable"
            /\ S_battery = "low"
            /\ S_low_battery_notification = "notified"
            /\ S_obstacle_detection_failure_notification = "notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked_notification = "notified"
            /\ S_communication = "stable"
            /\ S_battery = "low"
            /\ S_low_battery_notification = "notified"
            /\ S_obstacle_detection_failure_notification = "notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "no"
            /\ S_communication = "stable"
            /\ S_battery = "low"
            /\ S_low_battery_notification = "notified"
            /\ S_obstacle_detection_failure_notification = "notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "no"
            /\ S_communication = "stable"
            /\ S_battery = "low"
            /\ S_low_battery_notification = "notified"
            /\ S_obstacle_detection_failure_notification = "notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked_notification = "notified"
            /\ S_communication = "degraded"
            /\ S_communication_failure_notification = "notified"
            /\ S_battery = "ok"
            /\ S_obstacle_detection_failure_notification = "notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked_notification = "notified"
            /\ S_communication = "degraded"
            /\ S_communication_failure_notification = "notified"
            /\ S_battery = "ok"
            /\ S_obstacle_detection_failure_notification = "notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "no"
            /\ S_communication = "degraded"
            /\ S_communication_failure_notification = "notified"
            /\ S_battery = "ok"
            /\ S_obstacle_detection_failure_notification = "notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "no"
            /\ S_communication = "degraded"
            /\ S_communication_failure_notification = "notified"
            /\ S_battery = "ok"
            /\ S_obstacle_detection_failure_notification = "notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked_notification = "notified"
            /\ S_communication = "stable"
            /\ S_battery = "low"
            /\ S_low_battery_notification = "notified"
            /\ S_obstacle_detection = "stable"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked_notification = "notified"
            /\ S_communication = "stable"
            /\ S_battery = "low"
            /\ S_low_battery_notification = "notified"
            /\ S_obstacle_detection = "stable"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "no"
            /\ S_communication = "stable"
            /\ S_battery = "low"
            /\ S_low_battery_notification = "notified"
            /\ S_obstacle_detection = "stable"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "no"
            /\ S_communication = "stable"
            /\ S_battery = "low"
            /\ S_low_battery_notification = "notified"
            /\ S_obstacle_detection = "stable"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked_notification = "notified"
            /\ S_communication = "degraded"
            /\ S_communication_failure_notification = "notified"
            /\ S_battery = "ok"
            /\ S_obstacle_detection = "stable"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked_notification = "notified"
            /\ S_communication = "degraded"
            /\ S_communication_failure_notification = "notified"
            /\ S_battery = "ok"
            /\ S_obstacle_detection = "stable"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "no"
            /\ S_communication = "degraded"
            /\ S_communication_failure_notification = "notified"
            /\ S_battery = "ok"
            /\ S_obstacle_detection = "stable"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "no"
            /\ S_communication = "degraded"
            /\ S_communication_failure_notification = "notified"
            /\ S_battery = "ok"
            /\ S_obstacle_detection = "stable"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked_notification = "notified"
            /\ S_communication = "stable"
            /\ S_battery = "ok"
            /\ S_obstacle_detection_failure_notification = "notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked_notification = "notified"
            /\ S_communication = "stable"
            /\ S_battery = "ok"
            /\ S_obstacle_detection_failure_notification = "notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "no"
            /\ S_communication = "stable"
            /\ S_battery = "ok"
            /\ S_obstacle_detection_failure_notification = "notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "no"
            /\ S_communication = "stable"
            /\ S_battery = "ok"
            /\ S_obstacle_detection_failure_notification = "notified"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked_notification = "notified"
            /\ S_communication = "stable"
            /\ S_battery = "ok"
            /\ S_obstacle_detection = "stable"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked_notification = "notified"
            /\ S_communication = "stable"
            /\ S_battery = "ok"
            /\ S_obstacle_detection = "stable"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "no"
            /\ S_communication = "stable"
            /\ S_battery = "ok"
            /\ S_obstacle_detection = "stable"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "not_complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "no"
            /\ S_communication = "stable"
            /\ S_battery = "ok"
            /\ S_obstacle_detection = "stable"
            /\ S_mission_abort_request = "no"
configure_mission ==
        \/
            /\ S_flying = "flying"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked_notification = "notified"
            /\ S_communication = "stable"
            /\ S_battery = "ok"
            /\ S_obstacle_detection_failure_notification = "notified"
        \/
            /\ S_flying = "flying"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "no"
            /\ S_communication = "stable"
            /\ S_battery = "ok"
            /\ S_obstacle_detection_failure_notification = "notified"
        \/
            /\ S_flying = "flying"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked_notification = "notified"
            /\ S_communication = "stable"
            /\ S_battery = "ok"
            /\ S_obstacle_detection = "stable"
        \/
            /\ S_flying = "flying"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "no"
            /\ S_communication = "stable"
            /\ S_battery = "ok"
            /\ S_obstacle_detection = "stable"
        \/
            /\ S_flying = "flying"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked_notification = "notified"
            /\ S_communication_failure_notification = "notified"
            /\ S_battery = "ok"
            /\ S_obstacle_detection_failure_notification = "notified"
        \/
            /\ S_flying = "flying"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "no"
            /\ S_communication_failure_notification = "notified"
            /\ S_battery = "ok"
            /\ S_obstacle_detection_failure_notification = "notified"
        \/
            /\ S_flying = "flying"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked_notification = "notified"
            /\ S_communication_failure_notification = "notified"
            /\ S_battery = "ok"
            /\ S_obstacle_detection = "stable"
        \/
            /\ S_flying = "flying"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "no"
            /\ S_communication_failure_notification = "notified"
            /\ S_battery = "ok"
            /\ S_obstacle_detection = "stable"
        \/
            /\ S_flying = "flying"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked_notification = "notified"
            /\ S_communication = "stable"
            /\ S_low_battery_notification = "notified"
            /\ S_obstacle_detection_failure_notification = "notified"
        \/
            /\ S_flying = "flying"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "no"
            /\ S_communication = "stable"
            /\ S_low_battery_notification = "notified"
            /\ S_obstacle_detection_failure_notification = "notified"
        \/
            /\ S_flying = "flying"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked_notification = "notified"
            /\ S_communication = "stable"
            /\ S_low_battery_notification = "notified"
            /\ S_obstacle_detection = "stable"
        \/
            /\ S_flying = "flying"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "no"
            /\ S_communication = "stable"
            /\ S_low_battery_notification = "notified"
            /\ S_obstacle_detection = "stable"
        \/
            /\ S_flying = "flying"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked_notification = "notified"
            /\ S_communication_failure_notification = "notified"
            /\ S_low_battery_notification = "notified"
            /\ S_obstacle_detection_failure_notification = "notified"
        \/
            /\ S_flying = "flying"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "no"
            /\ S_communication_failure_notification = "notified"
            /\ S_low_battery_notification = "notified"
            /\ S_obstacle_detection_failure_notification = "notified"
        \/
            /\ S_flying = "flying"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked_notification = "notified"
            /\ S_communication_failure_notification = "notified"
            /\ S_low_battery_notification = "notified"
            /\ S_obstacle_detection = "stable"
        \/
            /\ S_flying = "flying"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_being_blocked = "no"
            /\ S_communication_failure_notification = "notified"
            /\ S_low_battery_notification = "notified"
            /\ S_obstacle_detection = "stable"
        \/
            /\ S_flying = "on_the_ground"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "stable"
            /\ S_battery = "ok"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "on_the_ground"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "stable"
            /\ S_battery = "low"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "on_the_ground"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "degraded"
            /\ S_battery = "ok"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "on_the_ground"
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "degraded"
            /\ S_battery = "low"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_communication = "lost"
        \/
            /\ S_flying = "flying"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_battery = "critical"
        \/
            /\ S_flying = "flying"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
            /\ S_mission_abort_request = "yes"
        \/
            /\ S_flying = "flying"
            /\ S_pylon_inspection = "complete"
            /\ S_manual_control_request = "off"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "yes"
wait_for_start ==
        \/
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "no"
            /\ S_communication = "stable"
            /\ S_battery = "ok"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "no"
            /\ S_communication = "stable"
            /\ S_battery = "low"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "no"
            /\ S_communication = "degraded"
            /\ S_battery = "ok"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "no"
            /\ S_communication = "degraded"
            /\ S_battery = "low"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "no"
            /\ S_communication = "stable"
            /\ S_battery = "ok"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "no"
            /\ S_communication = "stable"
            /\ S_battery = "low"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "no"
            /\ S_communication = "degraded"
            /\ S_battery = "ok"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "no"
            /\ S_communication = "degraded"
            /\ S_battery = "low"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "no"
            /\ S_communication = "stable"
            /\ S_battery = "ok"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "no"
            /\ S_communication = "stable"
            /\ S_battery = "low"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "no"
            /\ S_communication = "degraded"
            /\ S_battery = "ok"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_pylon_inspection = "not_complete"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "no"
            /\ S_communication = "degraded"
            /\ S_battery = "low"
            /\ S_mission_abort_request = "no"
        \/
            /\ S_flying = "flying"
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_mission_started = "no"
        \/
            /\ S_flying = "flying"
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "no"
        \/
            /\ S_flying = "flying"
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_mission_started = "no"
notify_being_blocked ==
        \/
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_being_blocked = "yes"
            /\ S_being_blocked_notification = "not_yet_notified"
            /\ S_communication = "stable"
        \/
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_being_blocked = "yes"
            /\ S_being_blocked_notification = "not_yet_notified"
            /\ S_communication = "degraded"
        \/
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_being_blocked = "yes"
            /\ S_being_blocked_notification = "not_yet_notified"
            /\ S_communication = "stable"
        \/
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_being_blocked = "yes"
            /\ S_being_blocked_notification = "not_yet_notified"
            /\ S_communication = "degraded"
        \/
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_being_blocked = "yes"
            /\ S_being_blocked_notification = "not_yet_notified"
            /\ S_communication = "stable"
        \/
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_being_blocked = "yes"
            /\ S_being_blocked_notification = "not_yet_notified"
            /\ S_communication = "degraded"
notify_communication_failure ==
        \/
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_communication = "degraded"
            /\ S_communication_failure_notification = "not_yet_notified"
        \/
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_communication = "degraded"
            /\ S_communication_failure_notification = "not_yet_notified"
        \/
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_communication = "degraded"
            /\ S_communication_failure_notification = "not_yet_notified"
notify_low_battery ==
        \/
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_communication = "stable"
            /\ S_battery = "low"
            /\ S_low_battery_notification = "not_yet_notified"
        \/
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_communication = "degraded"
            /\ S_battery = "low"
            /\ S_low_battery_notification = "not_yet_notified"
        \/
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_communication = "stable"
            /\ S_battery = "low"
            /\ S_low_battery_notification = "not_yet_notified"
        \/
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_communication = "degraded"
            /\ S_battery = "low"
            /\ S_low_battery_notification = "not_yet_notified"
        \/
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_communication = "stable"
            /\ S_battery = "low"
            /\ S_low_battery_notification = "not_yet_notified"
        \/
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_communication = "degraded"
            /\ S_battery = "low"
            /\ S_low_battery_notification = "not_yet_notified"
notify_critical_battery ==
        \/
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_communication = "stable"
            /\ S_battery = "critical"
            /\ S_critical_battery_notification = "not_yet_notified"
        \/
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_communication = "degraded"
            /\ S_battery = "critical"
            /\ S_critical_battery_notification = "not_yet_notified"
        \/
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_communication = "stable"
            /\ S_battery = "critical"
            /\ S_critical_battery_notification = "not_yet_notified"
        \/
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_communication = "degraded"
            /\ S_battery = "critical"
            /\ S_critical_battery_notification = "not_yet_notified"
        \/
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_communication = "stable"
            /\ S_battery = "critical"
            /\ S_critical_battery_notification = "not_yet_notified"
        \/
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_communication = "degraded"
            /\ S_battery = "critical"
            /\ S_critical_battery_notification = "not_yet_notified"
notify_obstacle_detection_failure ==
        \/
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_communication = "stable"
            /\ S_obstacle_detection = "lost"
            /\ S_obstacle_detection_failure_notification = "not_yet_notified"
        \/
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_communication = "degraded"
            /\ S_obstacle_detection = "lost"
            /\ S_obstacle_detection_failure_notification = "not_yet_notified"
        \/
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_communication = "stable"
            /\ S_obstacle_detection = "lost"
            /\ S_obstacle_detection_failure_notification = "not_yet_notified"
        \/
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_communication = "degraded"
            /\ S_obstacle_detection = "lost"
            /\ S_obstacle_detection_failure_notification = "not_yet_notified"
        \/
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_communication = "stable"
            /\ S_obstacle_detection = "lost"
            /\ S_obstacle_detection_failure_notification = "not_yet_notified"
        \/
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_communication = "degraded"
            /\ S_obstacle_detection = "lost"
            /\ S_obstacle_detection_failure_notification = "not_yet_notified"
reset_being_blocked_notification_status ==
        \/
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_being_blocked = "no"
            /\ S_being_blocked_notification = "notified"
        \/
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_being_blocked = "no"
            /\ S_being_blocked_notification = "notified"
        \/
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_being_blocked = "no"
            /\ S_being_blocked_notification = "notified"
reset_communication_failure_notification_status ==
        \/
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_communication = "stable"
            /\ S_communication_failure_notification = "notified"
        \/
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_communication = "stable"
            /\ S_communication_failure_notification = "notified"
        \/
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_communication = "stable"
            /\ S_communication_failure_notification = "notified"
reset_low_battery_notification_status ==
        \/
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_battery = "ok"
            /\ S_low_battery_notification = "notified"
        \/
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_battery = "critical"
            /\ S_low_battery_notification = "notified"
        \/
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_battery = "ok"
            /\ S_low_battery_notification = "notified"
        \/
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_battery = "critical"
            /\ S_low_battery_notification = "notified"
        \/
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_battery = "ok"
            /\ S_low_battery_notification = "notified"
        \/
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_battery = "critical"
            /\ S_low_battery_notification = "notified"
reset_critical_battery_notification_status ==
        \/
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_battery = "ok"
            /\ S_critical_battery_notification = "notified"
        \/
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_battery = "low"
            /\ S_critical_battery_notification = "notified"
        \/
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_battery = "ok"
            /\ S_critical_battery_notification = "notified"
        \/
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_battery = "low"
            /\ S_critical_battery_notification = "notified"
        \/
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_battery = "ok"
            /\ S_critical_battery_notification = "notified"
        \/
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_battery = "low"
            /\ S_critical_battery_notification = "notified"
reset_obstacle_detection_failure_notification_status ==
        \/
            /\ S_at_landing_position = "unknown"
            /\ S_mission_configuration = "not_configured"
            /\ S_obstacle_detection = "stable"
            /\ S_obstacle_detection_failure_notification = "notified"
        \/
            /\ S_at_landing_position = "yes"
            /\ S_mission_configuration = "configured"
            /\ S_obstacle_detection = "stable"
            /\ S_obstacle_detection_failure_notification = "notified"
        \/
            /\ S_at_landing_position = "no"
            /\ S_mission_configuration = "configured"
            /\ S_obstacle_detection = "stable"
            /\ S_obstacle_detection_failure_notification = "notified"

====
